server:
  port: 2002

# seata 配置
seata:
  # 使用那个事务组
  tx-service-group: my-tx-group
  service:
    # 事务组对应的集群事务
    vgroup-mapping.my-tx-group: seata-server
    # seata-server的地址
    grouplist.seata-server: 127.0.0.1:8091
  enabled: true

spring:
  main:
    allow-circular-references: true #开启循环依赖
  zipkin:
    base-url: http://127.0.0.1:9411/ #zipkin服务所在的地址
    discoveryClientEnabled: false
    sender:
      type: web #数据传输方式，web表示以HTTP报文形式向服务端发送数据
  sleuth:
    sampler:
      probability: 1.0  #收集数据百分比，默认0.1（10%）
    web:
      client:
        enabled: true

  application:
    name: seata-storage-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
      web-stat-filter:
        enabled: true
    dynamic:
      druid:
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000
        time-between-eviction-runs-millis: 2000
        min-evictable-idle-time-millis: 600000
        max-evictable-idle-time-millis: 900000
        validation-query: SELECT 1 FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        keep-alive: true
        aop-patterns: "com.guo.sharding.mapper.*"
        filters: stat,wall,slf4j
        connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.135.129:3306/seata_storage?useUnicode=true&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          username: root
          password: Root123!
        multi-datasource1:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.135.129:3306/demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          username: root
          password: Root123!

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-enums-package: com.example.seataorderservice2001.domain
  configuration:
    cache-enabled: false
    default-executor-type: reuse
    jdbc-type-for-null: 'null'
    lazy-loading-enabled: true
    local-cache-scope: session
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  mapper-locations: classpath:mapper/*Mapper.xml

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  config: classpath:logback-spring.xml