server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.135.129:8848,192.168.135.129:8858,192.168.135.129:8868 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'